############# English navigation ##############

# main menu
[[main]]
name = "主页"
pageRef = "/"
weight = 1

[[main]]
name = "关于我们"
pageRef = "/about"
weight = 2

[[main]]
name = "Elements"
pageRef = "/elements"
weight = 3

[[main]]
weight = 4
name = "Pages"

[[main]]
parent = "Pages"
name = "Blog"
pageRef = "/blog"

[[main]]
parent = "Pages"
name = "联系我们"
pageRef = "/contact"

[[main]]
parent = "Pages"
name = "Authors"
pageRef = "/authors"

[[main]]
parent = "Pages"
name = "Categories"
pageRef = "/categories"

[[main]]
parent = "Pages"
name = "404 Page"
pageRef = "/404"


# footer menu
[[footer]]
name = "关于我们"
pageRef = "/about"
weight = 1

[[footer]]
name = "Elements"
pageRef = "/elements"
weight = 2

[[footer]]
name = "隐私政策"
pageRef = "/privacy-policy"
weight = 3
